### PR TITLE
Fix small function

### PR DESCRIPTION
**Pull request by naveen521kk**
This called the wrong function. Make it call correct function.

### CODE REVIEW

**Comment by naveen521kk** [comment]
When do you plan to release things 😄 ?

**Comment by leifgehrmann** [comment]
@naveen521kk I could make a release now if you'd like. I was just about to start #27 (I was pretty much gonna copy the PR you made in cairocffi)

**Comment by naveen521kk** [comment]
Great! I would suggest to fix #27 if you are working on it. I thought I would do but totally forgot about it. It is not very urgent for me though.

**Comment by leifgehrmann** [comment]
@naveen521kk I've released pangocffi (v0.9.0) and pangocairocffi (v0.5.0).

**Pull request merged**
